"""league_round_update

Revision ID: 01bea077fcce
Revises: 105df4158516
Create Date: 2025-03-31 17:45:07.398406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bea077fcce'
down_revision = '105df4158516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('position_raw', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_relative_score', sa.Integer(), nullable=False),
    sa.Column('event_total_score', sa.Integer(), nullable=False),
    sa.Column('pdga_number', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('round_relative_score', sa.Integer(), nullable=False),
    sa.Column('round_total_score', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['course_layouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_results_id'), 'event_results', ['id'], unique=False)
    op.drop_column('course_layouts', 'length')
    op.drop_column('course_layouts', 'difficulty')
    op.drop_column('course_layouts', 'par')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_layouts', sa.Column('par', sa.INTEGER(), nullable=True))
    op.add_column('course_layouts', sa.Column('difficulty', sa.VARCHAR(), nullable=True))
    op.add_column('course_layouts', sa.Column('length', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_event_results_id'), table_name='event_results')
    op.drop_table('event_results')
    # ### end Alembic commands ###
