"""course_conditions

Revision ID: 105df4158516
Revises: 94a22b457718
Create Date: 2025-03-11 21:58:04.176361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105df4158516'
down_revision = '94a22b457718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('conditions', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('conditions_updated', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'conditions_updated')
    op.drop_column('courses', 'conditions')
    # ### end Alembic commands ###
