"""round_points

Revision ID: 279fbb3998cf
Revises: 5fffbb8c63c6
Create Date: 2025-05-02 19:07:15.144147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279fbb3998cf'
down_revision = '5fffbb8c63c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.drop_column('round_points')

    # ### end Alembic commands ###
