"""initial_tables

Revision ID: 2940c4327541
Revises: 
Create Date: 2025-07-20 22:17:10.684495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2940c4327541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('holes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('conditions', sa.String(), nullable=True),
    sa.Column('conditions_updated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('name', name=op.f('uq_courses_name'))
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('event_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the event session'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='Start date of the event session'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='End date of the event session'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Description of the event session'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_sessions'))
    )
    op.create_index(op.f('ix_event_sessions_id'), 'event_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_event_sessions_name'), 'event_sessions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('hashed_password', name=op.f('uq_users_hashed_password'))
    )
    op.create_table('course_layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_layouts_course_id_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_layouts'))
    )
    op.create_index(op.f('ix_course_layouts_id'), 'course_layouts', ['id'], unique=False)
    op.create_table('event_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('position_raw', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_relative_score', sa.Integer(), nullable=False),
    sa.Column('event_total_score', sa.Integer(), nullable=False),
    sa.Column('pdga_number', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('round_relative_score', sa.Integer(), nullable=False),
    sa.Column('round_total_score', sa.Integer(), nullable=False),
    sa.Column('round_points', sa.Float(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=False),
    sa.Column('course_layout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_layout_id'], ['course_layouts.id'], name=op.f('fk_event_results_course_layout_id_course_layouts')),
    sa.ForeignKeyConstraint(['event_session_id'], ['event_sessions.id'], name=op.f('fk_event_results_event_session_id_event_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_results')),
    sa.UniqueConstraint('date', 'username', name='uq_eventresult_date_username')
    )
    op.create_index(op.f('ix_event_results_id'), 'event_results', ['id'], unique=False)
    op.create_table('holes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('hole_name', sa.String(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['course_layouts.id'], name=op.f('fk_holes_layout_id_course_layouts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holes'))
    )
    op.create_index(op.f('ix_holes_id'), 'holes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holes_id'), table_name='holes')
    op.drop_table('holes')
    op.drop_index(op.f('ix_event_results_id'), table_name='event_results')
    op.drop_table('event_results')
    op.drop_index(op.f('ix_course_layouts_id'), table_name='course_layouts')
    op.drop_table('course_layouts')
    op.drop_table('users')
    op.drop_index(op.f('ix_event_sessions_name'), table_name='event_sessions')
    op.drop_index(op.f('ix_event_sessions_id'), table_name='event_sessions')
    op.drop_table('event_sessions')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
