"""autoincrement

Revision ID: 3cf561e274ca
Revises: 279fbb3998cf
Create Date: 2025-05-02 19:42:15.290861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf561e274ca'
down_revision = '279fbb3998cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
