"""course_links

Revision ID: 52393ebe4d1e
Revises: d8ecb5131eed
Create Date: 2025-03-03 20:13:13.599026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52393ebe4d1e'
down_revision = 'd8ecb5131eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'link')
    # ### end Alembic commands ###
