"""event_update

Revision ID: 5fffbb8c63c6
Revises: 7d8234194ee2
Create Date: 2025-04-29 21:06:52.123605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fffbb8c63c6'
down_revision = '7d8234194ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_layouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('par', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=True))

    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_layout_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_event_results_layout_id_course_layouts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_event_results_course_layout_id_course_layouts'), 'course_layouts', ['course_layout_id'], ['id'])
        batch_op.drop_column('layout_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_event_results_course_layout_id_course_layouts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_event_results_layout_id_course_layouts', 'course_layouts', ['layout_id'], ['id'])
        batch_op.drop_column('course_layout_id')

    with op.batch_alter_table('course_layouts', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('length')
        batch_op.drop_column('par')

    # ### end Alembic commands ###
