"""sessions_to_events

Revision ID: 81db86fea79c
Revises: e30ea7f6243e
Create Date: 2025-07-06 19:49:52.333875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81db86fea79c'
down_revision = 'e30ea7f6243e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_results', sa.Column('event_session_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_event_results_league_session_id_league_sessions'), 'event_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_results_event_session_id_league_sessions'), 'event_results', 'league_sessions', ['event_session_id'], ['id'])
    op.drop_column('event_results', 'league_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_results', sa.Column('league_session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_event_results_event_session_id_league_sessions'), 'event_results', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_results_league_session_id_league_sessions'), 'event_results', 'league_sessions', ['league_session_id'], ['id'])
    op.drop_column('event_results', 'event_session_id')
    # ### end Alembic commands ###
