"""course_links

Revision ID: 94a22b457718
Revises: d8ecb5131eed
Create Date: 2025-03-05 20:56:49.812081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a22b457718'
down_revision = 'd8ecb5131eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'link')
    # ### end Alembic commands ###
