"""league_round_update_v2

Revision ID: 95b51638aaad
Revises: 01bea077fcce
Create Date: 2025-04-03 21:24:28.294711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b51638aaad'
down_revision = '01bea077fcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.alter_column('position_raw',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.alter_column('position_raw',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
