"""Auto upgrade: sync schema with latest models

Revision ID: a88f017e2a08
Revises: 2940c4327541
Create Date: 2025-10-12 22:19:37.997354

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a88f017e2a08"
down_revision = "b73a1f9c2d4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_event_results_event_session_id_event_sessions"),
        "event_results",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_event_sessions_id"), table_name="event_sessions")
    op.drop_index(op.f("ix_event_sessions_name"), table_name="event_sessions")
    op.drop_table("event_sessions")
    op.add_column(
        "event_results", sa.Column("disc_event_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_event_results_disc_event_id_disc_events"),
        "event_results",
        "disc_events",
        ["disc_event_id"],
        ["id"],
    )
    op.drop_column("event_results", "event_session_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_results",
        sa.Column(
            "event_session_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_event_results_disc_event_id_disc_events"),
        "event_results",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_event_results_event_session_id_event_sessions"),
        "event_results",
        "event_sessions",
        ["event_session_id"],
        ["id"],
    )
    op.drop_column("event_results", "disc_event_id")
    op.create_table(
        "event_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Name of the event session",
        ),
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Start date of the event session",
        ),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="End date of the event session",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Description of the event session",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_sessions")),
    )
    op.create_index(
        op.f("ix_event_sessions_name"), "event_sessions", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_event_sessions_id"), "event_sessions", ["id"], unique=False
    )
    # ### end Alembic commands ###
