name: Back End Build
on:
  push:
    branches-ignore:
      - main
      - 'feature/**'
  pull_request:
    branches-ignore:
      - main
      - 'feature/**'
  workflow_dispatch:
jobs:
  Python-Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt
      - name: Run Python isort
        run: |
          isort ./src
      - name: Run Python black
        uses: psf/black@stable
        with:
          options: '--check --verbose'
          src: './src'
      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=.pylintrc --load-plugins pylint_pydantic $(git ls-files '**/*.py' | grep -v '^migrations/')
      - name: Set Environment Variables
        run: |
          echo "FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER }}" >> "$GITHUB_ENV"
          echo "FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}" >> "$GITHUB_ENV"
      - name: Test with pytest
        run: |
          pytest pytests/test_courses.py
